version: '3.8'

services:
  discord-music-bot:
    build: .
    container_name: music_bot
    restart: unless-stopped
    env_file:
      - .env
      - .env.factorio-control
    # --- EZT A 2 SORT KELL BEÍRNOD A VOLUMES FÖLÉ VAGY ALÁ ---
    networks:
      - umkgl-network
    # ---------------------------------------------------------
    ports:
      - "5050:5050"
    volumes:
      - ./sounds:/app/sounds
      - ./music:/app/music
      - ./jimmy:/app/jimmy
      - ./cookies.txt:/app/cookies.txt
      - ./quotes:/app/quotes
      - ./roulette_sounds:/app/roulette_sounds
      - ./scheduled_messages.json:/app/scheduled_messages.json
      - ./factorio_access_list.json:/app/factorio_access_list.json

  factorio-control-api:
    build:
      context: ./factorio-control-api
    container_name: factorio-control-api
    restart: unless-stopped
    env_file:
      - .env.factorio-control
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - umkgl-network

# --- EZT PEDIG A FÁJL LEGZSÁRÁRA (NEM BELJEBB HÚZVA!) ---
networks:
  umkgl-network:
    external: true
